spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///oyo
    hikari:
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:Root@123}
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      jdbc-url: jdbc:mysql:///oyo
      pool-name: oyo
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database: mysql
  jackson:
    time-zone: "Asia/Tokyo"
    serialization:
      WRITE_DATES_WITH_ZONE_ID: true